// Purpose: Predefined symptom list and associated icons used in forms and filters.
// File: lib/core/constants/symptoms.dart

import 'package:flutter/material.dart';

// --- Master symptom labels used in forms ---
final List<String> symptoms = [
  'Fever',
  'Headache',
  'Cough',
  'Back Pain',
  'Fatigue',
  'Chest Pain',
  'Nausea',
  'Vomiting',
  'Dizziness',
  'Shortness of Breath',
  'Sore Throat',
  'Runny Nose',
  'Joint Pain',
  'Muscle Pain',
  'Skin Rash',
  'Itching',
  'Abdominal Pain',
  'Diarrhea',
  'Constipation',
  'Loss of Appetite',
  'Weight Loss',
  'Weight Gain',
  'Swelling',
  'Blurred Vision',
  'Ear Pain',
  'Toothache',
  'Hair Loss',
  'Anxiety',
  'Depression',
  'Insomnia',
];

// --- Icon mapping for symptom badges ---
final Map<String, IconData> symptomIcons = {
  'Fever': Icons.thermostat,
  'Headache': Icons.health_and_safety,
  'Cough': Icons.air,
  'Back Pain': Icons.accessibility_new,
  'Fatigue': Icons.battery_alert,
  'Chest Pain': Icons.favorite,
  'Nausea': Icons.sick,
  'Vomiting': Icons.sick,
  'Dizziness': Icons.rotate_right,
  'Shortness of Breath': Icons.air,
  'Sore Throat': Icons.record_voice_over,
  'Runny Nose': Icons.water_drop,
  'Joint Pain': Icons.accessibility,
  'Muscle Pain': Icons.fitness_center,
  'Skin Rash': Icons.brush,
  'Itching': Icons.touch_app,
  'Abdominal Pain': Icons.restaurant,
  'Diarrhea': Icons.water_drop,
  'Constipation': Icons.block,
  'Loss of Appetite': Icons.no_food,
  'Weight Loss': Icons.monitor_weight,
  'Weight Gain': Icons.monitor_weight,
  'Swelling': Icons.circle,
  'Blurred Vision': Icons.visibility,
  'Ear Pain': Icons.hearing,
  'Toothache': Icons.medical_services,
  'Hair Loss': Icons.cut,
  'Anxiety': Icons.sentiment_dissatisfied,
  'Depression': Icons.sentiment_very_dissatisfied,
  'Insomnia': Icons.nightlight_round,
};
