// Purpose: Firebase configuration for all platforms (web, iOS, Android, etc.).
// File: lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // --- Resolve Firebase options for the active platform ---
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- Web Firebase config ---
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm-ovW5c_Hf9-4sXCFFmXHRNoxqizJj0I',
    appId: '1:573643929818:web:3b8d9c4987946466d20de3',
    messagingSenderId: '573643929818',
    projectId: 'aidlink-798fa',
    authDomain: 'aidlink-798fa.firebaseapp.com',
    storageBucket: 'aidlink-798fa.firebasestorage.app',
  );

  // --- Android Firebase config ---
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMH0vPr7YUvgAoiGdRj_dA8l8CYiGnIA',
    appId: '1:573643929818:android:c58f425a52a4ecf5d20de3',
    messagingSenderId: '573643929818',
    projectId: 'aidlink-798fa',
    storageBucket: 'aidlink-798fa.firebasestorage.app',
  );
}
